-- ════════════════════════════════════════════════════════════════════════
--  Catálogo de campos de las fichas de inspección — 14 tipos, 709 campos
--
--  GENERADO por gen_catalogo.py. No editar a mano: corregir el generador y
--  volver a emitirlo, o el próximo cambio pisa la corrección.
--
--  Las diez fichas son la misma plantilla con bloques intercambiables, así
--  que el catálogo declara cada campo UNA vez y lo expande a los tipos que
--  lo usan. Un mismo dato lleva el mismo nombre de campo en todos los tipos
--  ('ing_long' es la longitud de la transición de ingreso en canoa, sifón,
--  alcantarilla y desarenador), de modo que un reporte pueda cruzar tipos
--  sin traducir nombres.
--
--      docker exec -i jurp_postgis psql -U gis_admin -d jurp_gis \
--          < alta_catalogo_fichas.sql
--
--  Idempotente y autocorrectivo: inserta lo que falta y alinea lo que ya
--  está (etiqueta, tipo, dominio, obligatoriedad, orden). Correrlo dos veces
--  no duplica nada y deja la base igual a este archivo.
--
--  Si un código de tipo de activo no existe en tipos_activo, se avisa por
--  NOTICE y NO se inserta nada de ese tipo. Nunca queda a medias.
-- ════════════════════════════════════════════════════════════════════════

-- ── Diagnóstico: los tipos que hay en la base, para cotejar los códigos ──
SELECT codigo, nombre, evaluable FROM tipos_activo ORDER BY codigo;

BEGIN;

-- ── 1) Dominios ─────────────────────────────────────────────────────────
INSERT INTO dominios (dominio, codigo, etiqueta, orden)
SELECT v.dominio, v.codigo, v.etiqueta, v.orden
FROM (VALUES
  ('si_no', 'S', 'Sí', 1),
  ('si_no', 'N', 'No', 2),
  ('estado_brm', 'B', 'Bueno', 1),
  ('estado_brm', 'R', 'Regular', 2),
  ('estado_brm', 'M', 'Malo', 3),
  ('tipo_obra', 'Pe', 'Permanente', 1),
  ('tipo_obra', 'SR', 'Semi-rústico', 2),
  ('tipo_obra', 'Ru', 'Rústico', 3),
  ('tipo_obra', 'O', 'Otro', 4),
  ('material_obra', 'C', 'Concreto', 1),
  ('material_obra', 'M', 'Mampostería', 2),
  ('material_obra', 'MA', 'Madera', 3),
  ('material_obra', 'NP', 'No precisa', 4),
  ('material_obra', 'O', 'Otros', 5),
  ('revestimiento', 'C', 'Concreto', 1),
  ('revestimiento', 'M', 'Mampostería', 2),
  ('revestimiento', 'E', 'Enrocado', 3),
  ('revestimiento', 'T', 'Tierra', 4),
  ('revestimiento', 'O', 'Otro', 5),
  ('tipo_cuerpo', 'T', 'Tubería', 1),
  ('tipo_cuerpo', 'CA', 'Cajón', 2),
  ('tipo_cuerpo', 'O', 'Otro', 3),
  ('tipo_seccion', 'R', 'Rectangular', 1),
  ('tipo_seccion', 'T', 'Trapezoidal', 2),
  ('tipo_seccion', 'C', 'Circular', 3),
  ('tipo_seccion', 'O', 'Otro', 4),
  ('tipo_conduc', 'CA', 'Canal abierto', 1),
  ('tipo_conduc', 'TU', 'Tubería', 2),
  ('tipo_conduc', 'CC', 'Conducto cubierto', 3),
  ('tipo_conduc', 'O', 'Otro', 4),
  ('material_tub', 'A', 'Acero', 1),
  ('material_tub', 'C', 'Concreto', 2),
  ('material_tub', 'PV', 'PVC', 3),
  ('material_tub', 'AC', 'Asbesto/cemento', 4),
  ('material_tub', 'NP', 'No precisa', 5),
  ('material_tub', 'O', 'Otros', 6),
  ('mat_revest_can', 'C', 'Concreto', 1),
  ('mat_revest_can', 'M', 'Mampostería', 2),
  ('mat_revest_can', 'G', 'Geomembrana', 3),
  ('mat_revest_can', 'PV', 'PVC', 4),
  ('mat_revest_can', 'O', 'Otro', 5),
  ('mat_junta', 'E', 'Elastomérico', 1),
  ('mat_junta', 'A', 'Asfalto', 2),
  ('mat_junta', 'O', 'Otro', 3),
  ('tipo_medicion', 'P', 'Parshall', 1),
  ('tipo_medicion', 'SC', 'Sin cuello', 2),
  ('tipo_medicion', 'RBC', 'RBC', 3),
  ('tipo_medicion', 'O', 'Otros', 4),
  ('tipo_uso', 'A', 'Agrario', 1),
  ('tipo_uso', 'M', 'Multisectorial', 2),
  ('tipo_caida', 'SC', 'Sin caída', 1),
  ('tipo_caida', 'CV', 'Caída vertical', 2),
  ('tipo_caida', 'CI', 'Caída inclinada', 3),
  ('margen_cs', 'I', 'Izquierda', 1),
  ('margen_cs', 'D', 'Derecha', 2),
  ('margen_cs', 'A', 'Ambas', 3),
  ('tipo_red', 'TR', 'Troncal', 1),
  ('tipo_red', 'SE', 'Secundaria', 2),
  ('tipo_red', 'O', 'Otro', 3),
  ('tipo_operacion', 'M', 'Manual', 1),
  ('tipo_operacion', 'A', 'Automática', 2),
  ('tipo_operacion', '-', 'No precisa', 3)
) AS v(dominio, codigo, etiqueta, orden)
WHERE NOT EXISTS (
  SELECT 1 FROM dominios d
  WHERE d.dominio = v.dominio AND d.codigo = v.codigo
);

-- ── 2) El catálogo, declarado una sola vez ──────────────────────────────
-- Va en tabla temporal para que el INSERT y el UPDATE de alineación lean la
-- misma lista: mantener dos copias de cientos de filas es garantía de que
-- algún día una se quede atrás.
CREATE TEMP TABLE catalogo (
  tipo_activo text    NOT NULL,
  campo       text    NOT NULL,
  etiqueta    text    NOT NULL,
  tipo_dato   text    NOT NULL,
  dominio     text,
  obligatorio boolean NOT NULL,
  orden       integer NOT NULL,
  PRIMARY KEY (tipo_activo, campo)
) ON COMMIT DROP;

INSERT INTO catalogo VALUES
  ('alcantarilla', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('alcantarilla', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('alcantarilla', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('alcantarilla', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('alcantarilla', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('alcantarilla', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('alcantarilla', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('alcantarilla', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('alcantarilla', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('alcantarilla', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('alcantarilla', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('alcantarilla', 'ing_revest', 'Ingreso · revestimiento', 'opcion', 'revestimiento', false, 120),
  ('alcantarilla', 'ing_estado', 'Ingreso · estado', 'opcion', 'estado_brm', false, 130),
  ('alcantarilla', 'ing_long', 'Ingreso · longitud (m)', 'numero', NULL, false, 140),
  ('alcantarilla', 'ing_bmayor', 'Ingreso · base mayor B (m)', 'numero', NULL, false, 150),
  ('alcantarilla', 'ing_bmenor', 'Ingreso · base menor b (m)', 'numero', NULL, false, 160),
  ('alcantarilla', 'ing_h1', 'Ingreso · altura muro h1 (m)', 'numero', NULL, false, 170),
  ('alcantarilla', 'ing_h2', 'Ingreso · altura muro h2 (m)', 'numero', NULL, false, 180),
  ('alcantarilla', 'ing_espes', 'Ingreso · espesor e (m)', 'numero', NULL, false, 190),
  ('alcantarilla', 'cue_tipo', 'Cuerpo · tipo', 'opcion', 'tipo_cuerpo', false, 200),
  ('alcantarilla', 'cue_estado', 'Cuerpo · estado', 'opcion', 'estado_brm', false, 210),
  ('alcantarilla', 'cue_long', 'Cuerpo · longitud L (m)', 'numero', NULL, false, 220),
  ('alcantarilla', 'cue_diam', 'Cuerpo · diámetro Ø (m)', 'numero', NULL, false, 230),
  ('alcantarilla', 'cue_base', 'Cuerpo · base b (m)', 'numero', NULL, false, 240),
  ('alcantarilla', 'cue_altura', 'Cuerpo · altura h (m)', 'numero', NULL, false, 250),
  ('alcantarilla', 'cue_espes', 'Cuerpo · espesor e (m)', 'numero', NULL, false, 260),
  ('alcantarilla', 'cue_esplos', 'Cuerpo · espesor losa e1 (m)', 'numero', NULL, false, 270),
  ('alcantarilla', 'sal_revest', 'Salida · revestimiento', 'opcion', 'revestimiento', false, 280),
  ('alcantarilla', 'sal_estado', 'Salida · estado', 'opcion', 'estado_brm', false, 290),
  ('alcantarilla', 'sal_long', 'Salida · longitud (m)', 'numero', NULL, false, 300),
  ('alcantarilla', 'sal_bmayor', 'Salida · base mayor B (m)', 'numero', NULL, false, 310),
  ('alcantarilla', 'sal_bmenor', 'Salida · base menor b (m)', 'numero', NULL, false, 320),
  ('alcantarilla', 'sal_h3', 'Salida · altura muro h3 (m)', 'numero', NULL, false, 330),
  ('alcantarilla', 'sal_espes', 'Salida · espesor e (m)', 'numero', NULL, false, 340),
  ('alcantarilla', 'can_ing_hay', 'Canal de ingreso · ¿cuenta con canal?', 'opcion', 'si_no', false, 350),
  ('alcantarilla', 'can_ing_mat', 'Canal de ingreso · revestimiento', 'opcion', 'revestimiento', false, 360),
  ('alcantarilla', 'can_ing_estado', 'Canal de ingreso · estado', 'opcion', 'estado_brm', false, 370),
  ('alcantarilla', 'can_sal_hay', 'Canal de salida · ¿cuenta con canal?', 'opcion', 'si_no', false, 380),
  ('alcantarilla', 'can_sal_mat', 'Canal de salida · revestimiento', 'opcion', 'revestimiento', false, 390),
  ('alcantarilla', 'can_sal_estado', 'Canal de salida · estado', 'opcion', 'estado_brm', false, 400),
  ('alcantarilla', 'insp_operativa', 'Inspección · ¿La estructura se encuentra operativa?', 'opcion', 'si_no', true, 410),
  ('alcantarilla', 'insp_operativa_c', 'Inspección · ¿La estructura se encuentra operativa? — detalle', 'texto', NULL, false, 420),
  ('alcantarilla', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación de los cauces de ingreso y/o salida?', 'opcion', 'si_no', true, 430),
  ('alcantarilla', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación de los cauces de ingreso y/o salida? — detalle', 'texto', NULL, false, 440),
  ('alcantarilla', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 450),
  ('alcantarilla', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 460),
  ('alcantarilla', 'insp_obstruida', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)?', 'opcion', 'si_no', true, 470),
  ('alcantarilla', 'insp_obstruida_c', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)? — detalle', 'texto', NULL, false, 480),
  ('alcantarilla', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 490),
  ('aliviadero', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('aliviadero', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('aliviadero', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('aliviadero', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('aliviadero', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('aliviadero', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('aliviadero', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('aliviadero', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('aliviadero', 'apr_estado', 'Canal de ingreso · estado', 'opcion', 'estado_brm', false, 90),
  ('aliviadero', 'apr_qdis', 'Canal de ingreso · caudal de diseño (m³/s)', 'numero', NULL, false, 100),
  ('aliviadero', 'apr_qope', 'Canal de ingreso · caudal de operación (m³/s)', 'numero', NULL, false, 110),
  ('aliviadero', 'apr_base', 'Canal de ingreso · base b (m)', 'numero', NULL, false, 120),
  ('aliviadero', 'apr_hd', 'Canal de ingreso · altura derecha hd (m)', 'numero', NULL, false, 130),
  ('aliviadero', 'apr_zd', 'Canal de ingreso · talud derecho zd', 'numero', NULL, false, 140),
  ('aliviadero', 'apr_hi', 'Canal de ingreso · altura izquierda hi (m)', 'numero', NULL, false, 150),
  ('aliviadero', 'apr_zi', 'Canal de ingreso · talud izquierdo zi', 'numero', NULL, false, 160),
  ('aliviadero', 'ali_revest', 'Aliviadero · revestimiento', 'opcion', 'revestimiento', false, 170),
  ('aliviadero', 'ali_estado', 'Aliviadero · estado', 'opcion', 'estado_brm', false, 180),
  ('aliviadero', 'ali_long', 'Aliviadero · longitud (m)', 'numero', NULL, false, 190),
  ('aliviadero', 'ali_base', 'Aliviadero · base b (m)', 'numero', NULL, false, 200),
  ('aliviadero', 'ali_altura', 'Aliviadero · altura h (m)', 'numero', NULL, false, 210),
  ('aliviadero', 'ali_espes', 'Aliviadero · espesor e (m)', 'numero', NULL, false, 220),
  ('aliviadero', 'ali_talud', 'Aliviadero · talud Z (1:H)', 'numero', NULL, false, 230),
  ('aliviadero', 'par_estado', 'Partidor · estado', 'opcion', 'estado_brm', false, 240),
  ('aliviadero', 'par_long', 'Partidor · longitud (m)', 'numero', NULL, false, 250),
  ('aliviadero', 'par_base', 'Partidor · base b (m)', 'numero', NULL, false, 260),
  ('aliviadero', 'par_altura', 'Partidor · altura h (m)', 'numero', NULL, false, 270),
  ('aliviadero', 'par_espes', 'Partidor · espesor e (m)', 'numero', NULL, false, 280),
  ('aliviadero', 'par_compu', 'Partidor · ¿compuertas metálicas?', 'opcion', 'si_no', false, 290),
  ('aliviadero', 'par_baran', 'Partidor · ¿barandas de seguridad?', 'opcion', 'si_no', false, 300),
  ('aliviadero', 'sif_estado', 'Canal hacia el sifón · estado', 'opcion', 'estado_brm', false, 310),
  ('aliviadero', 'sif_long', 'Canal hacia el sifón · longitud (m)', 'numero', NULL, false, 320),
  ('aliviadero', 'sif_base', 'Canal hacia el sifón · base b (m)', 'numero', NULL, false, 330),
  ('aliviadero', 'sif_altura', 'Canal hacia el sifón · altura h (m)', 'numero', NULL, false, 340),
  ('aliviadero', 'sif_espes', 'Canal hacia el sifón · espesor e (m)', 'numero', NULL, false, 350),
  ('aliviadero', 'sif_talud', 'Canal hacia el sifón · talud Z (1:H)', 'numero', NULL, false, 360),
  ('aliviadero', 'exc_estado', 'Canal de excedencia · estado', 'opcion', 'estado_brm', false, 370),
  ('aliviadero', 'exc_long', 'Canal de excedencia · longitud (m)', 'numero', NULL, false, 380),
  ('aliviadero', 'exc_base', 'Canal de excedencia · base b (m)', 'numero', NULL, false, 390),
  ('aliviadero', 'exc_altura', 'Canal de excedencia · altura h (m)', 'numero', NULL, false, 400),
  ('aliviadero', 'exc_espes', 'Canal de excedencia · espesor e (m)', 'numero', NULL, false, 410),
  ('aliviadero', 'exc_talud', 'Canal de excedencia · talud Z (1:H)', 'numero', NULL, false, 420),
  ('aliviadero', 'dis_estado', 'Disipador · estado', 'opcion', 'estado_brm', false, 430),
  ('aliviadero', 'dis_a', 'Disipador · a (m)', 'numero', NULL, false, 440),
  ('aliviadero', 'dis_b', 'Disipador · b (m)', 'numero', NULL, false, 450),
  ('aliviadero', 'dis_c', 'Disipador · c (m)', 'numero', NULL, false, 460),
  ('aliviadero', 'dis_d', 'Disipador · d (m)', 'numero', NULL, false, 470),
  ('aliviadero', 'dis_e', 'Disipador · e (m)', 'numero', NULL, false, 480),
  ('aliviadero', 'dis_f', 'Disipador · f (m)', 'numero', NULL, false, 490),
  ('aliviadero', 'dis_g', 'Disipador · g (m)', 'numero', NULL, false, 500),
  ('aliviadero', 'dis_h', 'Disipador · h (m)', 'numero', NULL, false, 510),
  ('aliviadero', 'dis_i', 'Disipador · i (m)', 'numero', NULL, false, 520),
  ('aliviadero', 'dis_j', 'Disipador · j (m)', 'numero', NULL, false, 530),
  ('aliviadero', 'dis_k', 'Disipador · k (m)', 'numero', NULL, false, 540),
  ('aliviadero', 'tub_mat', 'Conducción · material de la tubería', 'opcion', 'material_tub', false, 550),
  ('aliviadero', 'tub_diam', 'Conducción · diámetro Ø (mm)', 'numero', NULL, false, 560),
  ('aliviadero', 'enr_hay', 'Enrocado de protección · ¿cuenta con?', 'opcion', 'si_no', false, 570),
  ('aliviadero', 'enr_estado', 'Enrocado de protección · estado', 'opcion', 'estado_brm', false, 580),
  ('aliviadero', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 590),
  ('aliviadero', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 600),
  ('aliviadero', 'insp_metal_cor', 'Inspección · ¿Las estructuras metálicas presentan corrosión?', 'opcion', 'si_no', true, 610),
  ('aliviadero', 'insp_metal_cor_c', 'Inspección · ¿Las estructuras metálicas presentan corrosión? — detalle', 'texto', NULL, false, 620),
  ('aliviadero', 'insp_sedimento', 'Inspección · ¿Se evidencian sedimentos en la estructura?', 'opcion', 'si_no', true, 630),
  ('aliviadero', 'insp_sedimento_c', 'Inspección · ¿Se evidencian sedimentos en la estructura? — detalle', 'texto', NULL, false, 640),
  ('aliviadero', 'insp_descarga', 'Inspección · ¿La zona de descarga del aliviadero se encuentra habilitada?', 'opcion', 'si_no', true, 650),
  ('aliviadero', 'insp_descarga_c', 'Inspección · ¿La zona de descarga del aliviadero se encuentra habilitada? — detalle', 'texto', NULL, false, 660),
  ('canoas', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('canoas', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('canoas', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('canoas', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('canoas', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('canoas', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('canoas', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('canoas', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('canoas', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('canoas', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('canoas', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('canoas', 'ing_revest', 'Ingreso · revestimiento', 'opcion', 'revestimiento', false, 120),
  ('canoas', 'ing_estado', 'Ingreso · estado', 'opcion', 'estado_brm', false, 130),
  ('canoas', 'ing_long', 'Ingreso · longitud (m)', 'numero', NULL, false, 140),
  ('canoas', 'ing_bmayor', 'Ingreso · base mayor B (m)', 'numero', NULL, false, 150),
  ('canoas', 'ing_bmenor', 'Ingreso · base menor b (m)', 'numero', NULL, false, 160),
  ('canoas', 'ing_h1', 'Ingreso · altura muro h1 (m)', 'numero', NULL, false, 170),
  ('canoas', 'ing_espes', 'Ingreso · espesor e (m)', 'numero', NULL, false, 180),
  ('canoas', 'ing_esplos', 'Ingreso · espesor losa e1 (m)', 'numero', NULL, false, 190),
  ('canoas', 'diq_hay', 'Diques de encauzamiento · ¿cuenta con?', 'opcion', 'si_no', false, 200),
  ('canoas', 'diq_mat', 'Diques de encauzamiento · material', 'opcion', 'revestimiento', false, 210),
  ('canoas', 'diq_estado', 'Diques de encauzamiento · estado', 'opcion', 'estado_brm', false, 220),
  ('canoas', 'diq_corona', 'Diques de encauzamiento · corona C (m)', 'numero', NULL, false, 230),
  ('canoas', 'diq_altura', 'Diques de encauzamiento · altura H (m)', 'numero', NULL, false, 240),
  ('canoas', 'diq_talud', 'Diques de encauzamiento · talud Z', 'numero', NULL, false, 250),
  ('canoas', 'cue_estado', 'Cuerpo canoa · estado', 'opcion', 'estado_brm', false, 260),
  ('canoas', 'cue_long', 'Cuerpo canoa · longitud L (m)', 'numero', NULL, false, 270),
  ('canoas', 'cue_base', 'Cuerpo canoa · base b (m)', 'numero', NULL, false, 280),
  ('canoas', 'cue_altura', 'Cuerpo canoa · altura h (m)', 'numero', NULL, false, 290),
  ('canoas', 'cue_espes', 'Cuerpo canoa · espesor e (m)', 'numero', NULL, false, 300),
  ('canoas', 'cue_esplos', 'Cuerpo canoa · espesor losa e1 (m)', 'numero', NULL, false, 310),
  ('canoas', 'poz_caida', 'Poza de disipación · tipo de caída', 'opcion', 'tipo_caida', false, 320),
  ('canoas', 'poz_estado', 'Poza de disipación · estado', 'opcion', 'estado_brm', false, 330),
  ('canoas', 'poz_long', 'Poza de disipación · longitud (m)', 'numero', NULL, false, 340),
  ('canoas', 'poz_base', 'Poza de disipación · base b (m)', 'numero', NULL, false, 350),
  ('canoas', 'poz_altura', 'Poza de disipación · altura h (m)', 'numero', NULL, false, 360),
  ('canoas', 'poz_espes', 'Poza de disipación · espesor e (m)', 'numero', NULL, false, 370),
  ('canoas', 'sal_revest', 'Salida · revestimiento', 'opcion', 'revestimiento', false, 380),
  ('canoas', 'sal_estado', 'Salida · estado', 'opcion', 'estado_brm', false, 390),
  ('canoas', 'sal_long', 'Salida · longitud (m)', 'numero', NULL, false, 400),
  ('canoas', 'sal_bmayor', 'Salida · base mayor B (m)', 'numero', NULL, false, 410),
  ('canoas', 'sal_bmenor', 'Salida · base menor b (m)', 'numero', NULL, false, 420),
  ('canoas', 'sal_h2', 'Salida · altura muro h2 (m)', 'numero', NULL, false, 430),
  ('canoas', 'sal_espes', 'Salida · espesor e (m)', 'numero', NULL, false, 440),
  ('canoas', 'sal_esplos', 'Salida · espesor losa e1 (m)', 'numero', NULL, false, 450),
  ('canoas', 'can_sal_hay', 'Canal de salida · ¿cuenta con canal?', 'opcion', 'si_no', false, 460),
  ('canoas', 'can_sal_mat', 'Canal de salida · revestimiento', 'opcion', 'revestimiento', false, 470),
  ('canoas', 'can_sal_estado', 'Canal de salida · estado', 'opcion', 'estado_brm', false, 480),
  ('canoas', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 490),
  ('canoas', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 500),
  ('canoas', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación?', 'opcion', 'si_no', true, 510),
  ('canoas', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación? — detalle', 'texto', NULL, false, 520),
  ('canoas', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 530),
  ('canoas', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 540),
  ('canoas', 'insp_obstruida', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)?', 'opcion', 'si_no', true, 550),
  ('canoas', 'insp_obstruida_c', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)? — detalle', 'texto', NULL, false, 560),
  ('canoas', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 570),
  ('desarenadores', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('desarenadores', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('desarenadores', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('desarenadores', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('desarenadores', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('desarenadores', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('desarenadores', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('desarenadores', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('desarenadores', 'apr_tipo', 'Aproximación · tipo', 'opcion', 'tipo_conduc', false, 90),
  ('desarenadores', 'apr_estado', 'Aproximación · estado', 'opcion', 'estado_brm', false, 100),
  ('desarenadores', 'apr_long', 'Aproximación · longitud (m)', 'numero', NULL, false, 110),
  ('desarenadores', 'apr_ancho', 'Aproximación · ancho (m)', 'numero', NULL, false, 120),
  ('desarenadores', 'apr_altura', 'Aproximación · altura (m)', 'numero', NULL, false, 130),
  ('desarenadores', 'apr_espes', 'Aproximación · espesor e (m)', 'numero', NULL, false, 140),
  ('desarenadores', 'reg_estado', 'Regulación · estado', 'opcion', 'estado_brm', false, 150),
  ('desarenadores', 'reg_naves', 'Regulación · número de naves', 'entero', NULL, false, 160),
  ('desarenadores', 'reg_long', 'Regulación · longitud (m)', 'numero', NULL, false, 170),
  ('desarenadores', 'reg_base', 'Regulación · base b (m)', 'numero', NULL, false, 180),
  ('desarenadores', 'reg_altura', 'Regulación · altura h (m)', 'numero', NULL, false, 190),
  ('desarenadores', 'reg_espes', 'Regulación · espesor e (m)', 'numero', NULL, false, 200),
  ('desarenadores', 'reg_bmayor', 'Regulación · base mayor B (m)', 'numero', NULL, false, 210),
  ('desarenadores', 'reg_compu', 'Regulación · ¿compuertas metálicas?', 'opcion', 'si_no', false, 220),
  ('desarenadores', 'reg_baran', 'Regulación · ¿barandas de seguridad?', 'opcion', 'si_no', false, 230),
  ('desarenadores', 'ent_naves', 'Transición de entrada · número de naves', 'entero', NULL, false, 240),
  ('desarenadores', 'ent_long', 'Transición de entrada · longitud (m)', 'numero', NULL, false, 250),
  ('desarenadores', 'ent_bmayor', 'Transición de entrada · base mayor B (m)', 'numero', NULL, false, 260),
  ('desarenadores', 'ent_bmenor', 'Transición de entrada · base menor b (m)', 'numero', NULL, false, 270),
  ('desarenadores', 'ent_altura', 'Transición de entrada · altura h (m)', 'numero', NULL, false, 280),
  ('desarenadores', 'ent_espes', 'Transición de entrada · espesor e (m)', 'numero', NULL, false, 290),
  ('desarenadores', 'tan_estado', 'Tanque sedimentador · estado', 'opcion', 'estado_brm', false, 300),
  ('desarenadores', 'tan_naves', 'Tanque sedimentador · número de naves', 'entero', NULL, false, 310),
  ('desarenadores', 'tan_long', 'Tanque sedimentador · longitud (m)', 'numero', NULL, false, 320),
  ('desarenadores', 'tan_base', 'Tanque sedimentador · base b (m)', 'numero', NULL, false, 330),
  ('desarenadores', 'tan_basec', 'Tanque sedimentador · base c (m)', 'numero', NULL, false, 340),
  ('desarenadores', 'tan_altura', 'Tanque sedimentador · altura h (m)', 'numero', NULL, false, 350),
  ('desarenadores', 'tan_espes', 'Tanque sedimentador · espesor e (m)', 'numero', NULL, false, 360),
  ('desarenadores', 'tan_h1', 'Tanque sedimentador · altura h1 (m)', 'numero', NULL, false, 370),
  ('desarenadores', 'tan_h2', 'Tanque sedimentador · altura h2 (m)', 'numero', NULL, false, 380),
  ('desarenadores', 'tan_h3', 'Tanque sedimentador · altura h3 (m)', 'numero', NULL, false, 390),
  ('desarenadores', 'sal_estado', 'Transición de salida · estado', 'opcion', 'estado_brm', false, 400),
  ('desarenadores', 'sal_long', 'Transición de salida · longitud (m)', 'numero', NULL, false, 410),
  ('desarenadores', 'sal_base', 'Transición de salida · base b (m)', 'numero', NULL, false, 420),
  ('desarenadores', 'sal_basec', 'Transición de salida · base c (m)', 'numero', NULL, false, 430),
  ('desarenadores', 'sal_altura', 'Transición de salida · altura h (m)', 'numero', NULL, false, 440),
  ('desarenadores', 'sal_espes', 'Transición de salida · espesor e (m)', 'numero', NULL, false, 450),
  ('desarenadores', 'eq_puente', 'Equipamiento · ¿puente de maniobras?', 'opcion', 'si_no', false, 460),
  ('desarenadores', 'eq_purga', 'Equipamiento · ¿conductos de purga?', 'opcion', 'si_no', false, 470),
  ('desarenadores', 'eq_pdiam', 'Equipamiento · diámetro de purga (mm)', 'numero', NULL, false, 480),
  ('desarenadores', 'eq_pnum', 'Equipamiento · número de conductos de purga', 'entero', NULL, false, 490),
  ('desarenadores', 'eq_compu', 'Equipamiento · ¿compuertas metálicas?', 'opcion', 'si_no', false, 500),
  ('desarenadores', 'eq_cnum', 'Equipamiento · número de compuertas', 'entero', NULL, false, 510),
  ('desarenadores', 'cam_estado', 'Cámara de carga · estado', 'opcion', 'estado_brm', false, 520),
  ('desarenadores', 'cam_long', 'Cámara de carga · longitud (m)', 'numero', NULL, false, 530),
  ('desarenadores', 'cam_base', 'Cámara de carga · base b (m)', 'numero', NULL, false, 540),
  ('desarenadores', 'cam_basec', 'Cámara de carga · base c (m)', 'numero', NULL, false, 550),
  ('desarenadores', 'cam_altura', 'Cámara de carga · altura h (m)', 'numero', NULL, false, 560),
  ('desarenadores', 'cam_espes', 'Cámara de carga · espesor e (m)', 'numero', NULL, false, 570),
  ('desarenadores', 'cam_otros', 'Cámara de carga · otros', 'texto', NULL, false, 580),
  ('desarenadores', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 590),
  ('desarenadores', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 600),
  ('desarenadores', 'insp_metal_cor', 'Inspección · ¿Las estructuras metálicas presentan corrosión?', 'opcion', 'si_no', true, 610),
  ('desarenadores', 'insp_metal_cor_c', 'Inspección · ¿Las estructuras metálicas presentan corrosión? — detalle', 'texto', NULL, false, 620),
  ('desarenadores', 'insp_sedimento', 'Inspección · ¿Se evidencian sedimentos en la estructura?', 'opcion', 'si_no', true, 630),
  ('desarenadores', 'insp_sedimento_c', 'Inspección · ¿Se evidencian sedimentos en la estructura? — detalle', 'texto', NULL, false, 640),
  ('desarenadores', 'insp_averia', 'Inspección · ¿Presenta alguna avería?', 'opcion', 'si_no', true, 650),
  ('desarenadores', 'insp_averia_c', 'Inspección · ¿Presenta alguna avería? — detalle', 'texto', NULL, false, 660),
  ('entregas', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('entregas', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('entregas', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('entregas', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('entregas', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('entregas', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('entregas', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('entregas', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('entregas', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('entregas', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('entregas', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('entregas', 'ent_long1', 'Dimensiones · longitud L1 (m)', 'numero', NULL, false, 120),
  ('entregas', 'ent_long2', 'Dimensiones · longitud L2 (m)', 'numero', NULL, false, 130),
  ('entregas', 'ent_long3', 'Dimensiones · longitud L3 (m)', 'numero', NULL, false, 140),
  ('entregas', 'ent_ancho', 'Dimensiones · ancho b (m)', 'numero', NULL, false, 150),
  ('entregas', 'ent_bmayor', 'Dimensiones · ancho mayor B (m)', 'numero', NULL, false, 160),
  ('entregas', 'ent_altura', 'Dimensiones · altura h (m)', 'numero', NULL, false, 170),
  ('entregas', 'ent_espes', 'Dimensiones · espesor de muro e (m)', 'texto', NULL, false, 180),
  ('entregas', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 190),
  ('entregas', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 200),
  ('entregas', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación?', 'opcion', 'si_no', true, 210),
  ('entregas', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación? — detalle', 'texto', NULL, false, 220),
  ('entregas', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 230),
  ('entregas', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 240),
  ('entregas', 'insp_obstruida', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)?', 'opcion', 'si_no', true, 250),
  ('entregas', 'insp_obstruida_c', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)? — detalle', 'texto', NULL, false, 260),
  ('entregas', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 270),
  ('laterales', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('laterales', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('laterales', 'prog_ini', 'Ubicación · progresiva inicio', 'texto', NULL, false, 30),
  ('laterales', 'prog_fin', 'Ubicación · progresiva fin', 'texto', NULL, false, 40),
  ('laterales', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('laterales', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('laterales', 'tipo', 'Obra · tipo de sección', 'opcion', 'tipo_seccion', false, 70),
  ('laterales', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('laterales', 'q_diseno', 'Caudales · de diseño (m³/s)', 'numero', NULL, false, 90),
  ('laterales', 'operación', 'Caudales · de operación (m³/s)', 'numero', NULL, false, 100),
  ('laterales', 'uso', 'Caudales · tipo de uso', 'opcion', 'tipo_uso', false, 110),
  ('laterales', 'n__usuario', 'Caudales · n° de usuarios', 'entero', NULL, false, 120),
  ('laterales', 'Área_tota', 'Caudales · área total (ha)', 'numero', NULL, false, 130),
  ('laterales', 'area_riego', 'Caudales · área bajo riego (ha)', 'numero', NULL, false, 140),
  ('laterales', 'vol_otorg', 'Caudales · volumen otorgado (m³)', 'numero', NULL, false, 150),
  ('laterales', 'cap_vent', 'Caudales · n° de ventanas de captación', 'entero', NULL, false, 160),
  ('laterales', 'med_hay', 'Medición · ¿hay estructura al inicio?', 'opcion', 'si_no', false, 170),
  ('laterales', 'med_tipo', 'Medición · tipo', 'opcion', 'tipo_medicion', false, 180),
  ('laterales', 'med_otro', 'Medición · otro (especificar)', 'texto', NULL, false, 190),
  ('laterales', 'med_estado', 'Medición · estado', 'opcion', 'estado_brm', false, 200),
  ('laterales', 'cs_hay', 'Camino de servicio · ¿existe?', 'opcion', 'si_no', false, 210),
  ('laterales', 'cs_margen', 'Camino de servicio · margen', 'opcion', 'margen_cs', false, 220),
  ('laterales', 'cs_estado', 'Camino de servicio · estado', 'opcion', 'estado_brm', false, 230),
  ('laterales', 'rev_tipo', 'Revestimiento · ¿revestido o en tierra?', 'opcion', 'tipo_conduc', false, 240),
  ('laterales', 'rev_mat', 'Revestimiento · material', 'opcion', 'mat_revest_can', false, 250),
  ('laterales', 'rev_estado', 'Revestimiento · estado', 'opcion', 'estado_brm', false, 260),
  ('laterales', 'rev_obs', 'Revestimiento · observación', 'texto', NULL, false, 270),
  ('laterales', 'jun_hay', 'Juntas · ¿existen?', 'opcion', 'si_no', false, 280),
  ('laterales', 'jun_estado', 'Juntas · estado', 'opcion', 'estado_brm', false, 290),
  ('laterales', 'jun_separ', 'Juntas · separación (m)', 'numero', NULL, false, 300),
  ('laterales', 'jun_espes', 'Juntas · espesor (m)', 'numero', NULL, false, 310),
  ('laterales', 'jun_mat', 'Juntas · material', 'opcion', 'mat_junta', false, 320),
  ('laterales', 'eh_canoa', 'Obras en el tramo · canoas (und.)', 'entero', NULL, false, 330),
  ('laterales', 'eh_alcant', 'Obras en el tramo · alcantarillas (und.)', 'entero', NULL, false, 340),
  ('laterales', 'eh_entreg', 'Obras en el tramo · entregas (und.)', 'entero', NULL, false, 350),
  ('laterales', 'número_to', 'Obras en el tramo · tomas (und.)', 'entero', NULL, false, 360),
  ('laterales', 'eh_ppeat', 'Obras en el tramo · puentes peatonales (und.)', 'entero', NULL, false, 370),
  ('laterales', 'eh_pveh', 'Obras en el tramo · puentes vehiculares (und.)', 'entero', NULL, false, 380),
  ('laterales', 'eh_reten', 'Obras en el tramo · retenciones (und.)', 'entero', NULL, false, 390),
  ('laterales', 'eh_pases', 'Obras en el tramo · pases de tubería (und.)', 'entero', NULL, false, 400),
  ('laterales', 'eh_otros', 'Obras en el tramo · otros', 'texto', NULL, false, 410),
  ('laterales', 'esc_hay', 'Escalines · ¿existen?', 'opcion', 'si_no', false, 420),
  ('laterales', 'esc_estado', 'Escalines · estado', 'opcion', 'estado_brm', false, 430),
  ('laterales', 'esc_mat', 'Escalines · material', 'texto', NULL, false, 440),
  ('laterales', 'dim_b', 'Sección · base b (m)', 'numero', NULL, false, 450),
  ('laterales', 'dim_bmay', 'Sección · base mayor B (m)', 'numero', NULL, false, 460),
  ('laterales', 'dim_c', 'Sección · c (m)', 'numero', NULL, false, 470),
  ('laterales', 'dim_e', 'Sección · espesor e (m)', 'numero', NULL, false, 480),
  ('laterales', 'dim_y', 'Sección · tirante y (m)', 'numero', NULL, false, 490),
  ('laterales', 'dim_bi', 'Sección · berma izquierda BI (m)', 'numero', NULL, false, 500),
  ('laterales', 'dim_bd', 'Sección · berma derecha BD (m)', 'numero', NULL, false, 510),
  ('laterales', 'dim_cs', 'Sección · camino de servicio CS (m)', 'numero', NULL, false, 520),
  ('laterales', 'dim_x', 'Sección · x (m)', 'numero', NULL, false, 530),
  ('laterales', 'dim_diam', 'Sección · diámetro Ø (m)', 'numero', NULL, false, 540),
  ('laterales', 'dim_z', 'Sección · talud z (1:H)', 'texto', NULL, false, 550),
  ('laterales', 'dim_pend', 'Sección · pendiente S (%)', 'numero', NULL, false, 560),
  ('laterales', 'insp_revest', 'Inspección · ¿Problemas en el revestimiento (fisuras, desgaste)?', 'opcion', 'si_no', true, 570),
  ('laterales', 'insp_revest_c', 'Inspección · ¿Problemas en el revestimiento (fisuras, desgaste)? — detalle', 'texto', NULL, false, 580),
  ('laterales', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación?', 'opcion', 'si_no', true, 590),
  ('laterales', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación? — detalle', 'texto', NULL, false, 600),
  ('laterales', 'insp_mant_cs', 'Inspección · ¿Se evidencia mantenimiento del camino de servicio?', 'opcion', 'si_no', true, 610),
  ('laterales', 'insp_mant_cs_c', 'Inspección · ¿Se evidencia mantenimiento del camino de servicio? — detalle', 'texto', NULL, false, 620),
  ('laterales', 'insp_bermas', 'Inspección · ¿Las bermas se encuentran definidas?', 'opcion', 'si_no', true, 630),
  ('laterales', 'insp_bermas_c', 'Inspección · ¿Las bermas se encuentran definidas? — detalle', 'texto', NULL, false, 640),
  ('laterales', 'insp_riesgo', 'Inspección · ¿Existen zonas de riesgo en el tramo (deslizamiento, asentamiento, arenamiento)?', 'opcion', 'si_no', true, 650),
  ('laterales', 'insp_riesgo_c', 'Inspección · ¿Existen zonas de riesgo en el tramo (deslizamiento, asentamiento, arenamiento)? — detalle', 'texto', NULL, false, 660),
  ('laterales', 'insp_pintado', 'Inspección · ¿Existe el pintado de progresivas y señalética en el tramo?', 'opcion', 'si_no', true, 670),
  ('laterales', 'insp_pintado_c', 'Inspección · ¿Existe el pintado de progresivas y señalética en el tramo? — detalle', 'texto', NULL, false, 680),
  ('laterales', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 690),
  ('partidor', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('partidor', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('partidor', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('partidor', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('partidor', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('partidor', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('partidor', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('partidor', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('partidor', 'par_estado', 'Dimensiones · estado', 'opcion', 'estado_brm', false, 90),
  ('partidor', 'par_long', 'Dimensiones · longitud (m)', 'numero', NULL, false, 100),
  ('partidor', 'par_base', 'Dimensiones · base b (m)', 'numero', NULL, false, 110),
  ('partidor', 'par_altura', 'Dimensiones · altura h (m)', 'numero', NULL, false, 120),
  ('partidor', 'par_espes', 'Dimensiones · espesor e (m)', 'numero', NULL, false, 130),
  ('partidor', 'par_compu', 'Dimensiones · ¿compuertas metálicas?', 'opcion', 'si_no', false, 140),
  ('partidor', 'par_baran', 'Dimensiones · ¿barandas de seguridad?', 'opcion', 'si_no', false, 150),
  ('partidor', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 160),
  ('partidor', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 170),
  ('partidor', 'insp_metal_cor', 'Inspección · ¿Las estructuras metálicas presentan corrosión?', 'opcion', 'si_no', true, 180),
  ('partidor', 'insp_metal_cor_c', 'Inspección · ¿Las estructuras metálicas presentan corrosión? — detalle', 'texto', NULL, false, 190),
  ('partidor', 'insp_sedimento', 'Inspección · ¿Se evidencian sedimentos en la estructura?', 'opcion', 'si_no', true, 200),
  ('partidor', 'insp_sedimento_c', 'Inspección · ¿Se evidencian sedimentos en la estructura? — detalle', 'texto', NULL, false, 210),
  ('partidor', 'insp_averia', 'Inspección · ¿Presenta alguna avería?', 'opcion', 'si_no', true, 220),
  ('partidor', 'insp_averia_c', 'Inspección · ¿Presenta alguna avería? — detalle', 'texto', NULL, false, 230),
  ('partidor', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 240),
  ('puente_peatonal', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('puente_peatonal', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('puente_peatonal', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('puente_peatonal', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('puente_peatonal', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('puente_peatonal', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('puente_peatonal', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('puente_peatonal', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('puente_peatonal', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('puente_peatonal', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('puente_peatonal', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('puente_peatonal', 'pue_ancho', 'Dimensiones · ancho A (m)', 'numero', NULL, false, 120),
  ('puente_peatonal', 'pue_mgmay', 'Dimensiones · murete guarda mayor B (m)', 'numero', NULL, false, 130),
  ('puente_peatonal', 'pue_mgmen', 'Dimensiones · murete guarda menor b (m)', 'numero', NULL, false, 140),
  ('puente_peatonal', 'pue_long', 'Dimensiones · longitud L (m)', 'numero', NULL, false, 150),
  ('puente_peatonal', 'pue_translo', 'Dimensiones · transición de losa l (m)', 'numero', NULL, false, 160),
  ('puente_peatonal', 'pue_altura', 'Dimensiones · altura h (m)', 'numero', NULL, false, 170),
  ('puente_peatonal', 'pue_esplos', 'Dimensiones · espesor de losa e (m)', 'numero', NULL, false, 180),
  ('puente_peatonal', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 190),
  ('puente_peatonal', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 200),
  ('puente_peatonal', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación?', 'opcion', 'si_no', true, 210),
  ('puente_peatonal', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación? — detalle', 'texto', NULL, false, 220),
  ('puente_peatonal', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 230),
  ('puente_peatonal', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 240),
  ('puente_peatonal', 'insp_obstruida', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)?', 'opcion', 'si_no', true, 250),
  ('puente_peatonal', 'insp_obstruida_c', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)? — detalle', 'texto', NULL, false, 260),
  ('puente_peatonal', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 270),
  ('puente_vehicular', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('puente_vehicular', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('puente_vehicular', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('puente_vehicular', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('puente_vehicular', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('puente_vehicular', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('puente_vehicular', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('puente_vehicular', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('puente_vehicular', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('puente_vehicular', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('puente_vehicular', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('puente_vehicular', 'pue_ancho', 'Dimensiones · ancho A (m)', 'numero', NULL, false, 120),
  ('puente_vehicular', 'pue_mgmay', 'Dimensiones · murete guarda mayor B (m)', 'numero', NULL, false, 130),
  ('puente_vehicular', 'pue_mgmen', 'Dimensiones · murete guarda menor b (m)', 'numero', NULL, false, 140),
  ('puente_vehicular', 'pue_long', 'Dimensiones · longitud L (m)', 'numero', NULL, false, 150),
  ('puente_vehicular', 'pue_translo', 'Dimensiones · transición de losa l (m)', 'numero', NULL, false, 160),
  ('puente_vehicular', 'pue_altura', 'Dimensiones · altura h (m)', 'numero', NULL, false, 170),
  ('puente_vehicular', 'pue_esplos', 'Dimensiones · espesor de losa e (m)', 'numero', NULL, false, 180),
  ('puente_vehicular', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 190),
  ('puente_vehicular', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 200),
  ('puente_vehicular', 'insp_colmatada', 'Inspección · ¿Se evidencia colmatación?', 'opcion', 'si_no', true, 210),
  ('puente_vehicular', 'insp_colmatada_c', 'Inspección · ¿Se evidencia colmatación? — detalle', 'texto', NULL, false, 220),
  ('puente_vehicular', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 230),
  ('puente_vehicular', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 240),
  ('puente_vehicular', 'insp_obstruida', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)?', 'opcion', 'si_no', true, 250),
  ('puente_vehicular', 'insp_obstruida_c', 'Inspección · ¿La estructura se encuentra obstruida (ingreso y salida)? — detalle', 'texto', NULL, false, 260),
  ('puente_vehicular', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 270),
  ('sifon', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('sifon', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('sifon', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('sifon', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('sifon', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('sifon', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('sifon', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('sifon', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('sifon', 'material', 'Obra · material', 'opcion', 'material_tub', false, 90),
  ('sifon', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('sifon', 'mat_espes', 'Obra · espesor del acero (mm)', 'numero', NULL, false, 110),
  ('sifon', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 120),
  ('sifon', 'ing_revest', 'Ingreso · revestimiento', 'opcion', 'revestimiento', false, 130),
  ('sifon', 'ing_estado', 'Ingreso · estado', 'opcion', 'estado_brm', false, 140),
  ('sifon', 'ing_long', 'Ingreso · longitud (m)', 'numero', NULL, false, 150),
  ('sifon', 'ing_bmayor', 'Ingreso · base mayor B (m)', 'numero', NULL, false, 160),
  ('sifon', 'ing_bmenor', 'Ingreso · base menor b (m)', 'numero', NULL, false, 170),
  ('sifon', 'ing_h1', 'Ingreso · altura muro h1 (m)', 'numero', NULL, false, 180),
  ('sifon', 'ing_h2', 'Ingreso · altura muro h2 (m)', 'numero', NULL, false, 190),
  ('sifon', 'ing_espes', 'Ingreso · espesor e (m)', 'numero', NULL, false, 200),
  ('sifon', 'rej_ing_hay', 'Rejilla de ingreso · ¿cuenta con?', 'opcion', 'si_no', false, 210),
  ('sifon', 'rej_ing_est', 'Rejilla de ingreso · estado', 'opcion', 'estado_brm', false, 220),
  ('sifon', 'rej_ing_lon', 'Rejilla de ingreso · longitud (m)', 'numero', NULL, false, 230),
  ('sifon', 'rej_ing_alt', 'Rejilla de ingreso · alto (m)', 'numero', NULL, false, 240),
  ('sifon', 'cue_tipo', 'Ducto · tipo', 'opcion', 'tipo_cuerpo', false, 250),
  ('sifon', 'cue_estado', 'Ducto · estado', 'opcion', 'estado_brm', false, 260),
  ('sifon', 'cue_long', 'Ducto · longitud L (m)', 'numero', NULL, false, 270),
  ('sifon', 'cue_diam', 'Ducto · diámetro Ø (m)', 'numero', NULL, false, 280),
  ('sifon', 'cue_base', 'Ducto · base b (m)', 'numero', NULL, false, 290),
  ('sifon', 'cue_altura', 'Ducto · altura h (m)', 'numero', NULL, false, 300),
  ('sifon', 'cue_espes', 'Ducto · espesor e (m)', 'numero', NULL, false, 310),
  ('sifon', 'cue_esplos', 'Ducto · espesor losa e1 (m)', 'numero', NULL, false, 320),
  ('sifon', 'cue_mat', 'Ducto · material de la tubería', 'opcion', 'material_tub', false, 330),
  ('sifon', 'cue_otro', 'Ducto · otro (especificar)', 'texto', NULL, false, 340),
  ('sifon', 'sal_revest', 'Salida · revestimiento', 'opcion', 'revestimiento', false, 350),
  ('sifon', 'sal_estado', 'Salida · estado', 'opcion', 'estado_brm', false, 360),
  ('sifon', 'sal_long', 'Salida · longitud (m)', 'numero', NULL, false, 370),
  ('sifon', 'sal_bmayor', 'Salida · base mayor B (m)', 'numero', NULL, false, 380),
  ('sifon', 'sal_bmenor', 'Salida · base menor b (m)', 'numero', NULL, false, 390),
  ('sifon', 'sal_h', 'Salida · altura muro h (m)', 'numero', NULL, false, 400),
  ('sifon', 'sal_h3', 'Salida · altura muro h3 (m)', 'numero', NULL, false, 410),
  ('sifon', 'sal_espes', 'Salida · espesor e (m)', 'numero', NULL, false, 420),
  ('sifon', 'rej_sal_hay', 'Salida · ¿cuenta con rejilla de seguridad?', 'opcion', 'si_no', false, 430),
  ('sifon', 'pur_hay', 'Purga · ¿cuenta con caja de inspección y purga?', 'opcion', 'si_no', false, 440),
  ('sifon', 'pur_mat', 'Purga · material de la caja', 'opcion', 'material_tub', false, 450),
  ('sifon', 'pur_ancho', 'Purga · ancho (m)', 'numero', NULL, false, 460),
  ('sifon', 'pur_largo', 'Purga · largo (m)', 'numero', NULL, false, 470),
  ('sifon', 'pur_altura', 'Purga · altura (m)', 'numero', NULL, false, 480),
  ('sifon', 'pur_espes', 'Purga · espesor (m)', 'numero', NULL, false, 490),
  ('sifon', 'pur_esc_hay', 'Purga · escalera metálica · ¿cuenta con?', 'opcion', 'si_no', false, 500),
  ('sifon', 'pur_esc_estado', 'Purga · escalera metálica · estado', 'opcion', 'estado_brm', false, 510),
  ('sifon', 'pur_valv', 'Purga · ¿válvula compuerta?', 'opcion', 'si_no', false, 520),
  ('sifon', 'pur_vdiam', 'Purga · diámetro de válvula (mm)', 'numero', NULL, false, 530),
  ('sifon', 'pur_desf', 'Purga · ¿tubería de desfogue?', 'opcion', 'si_no', false, 540),
  ('sifon', 'pur_ddiam', 'Purga · diámetro de desfogue (mm)', 'numero', NULL, false, 550),
  ('sifon', 'pur_rej_hay', 'Purga · rejilla de seguridad · ¿cuenta con?', 'opcion', 'si_no', false, 560),
  ('sifon', 'pur_rej_estado', 'Purga · rejilla de seguridad · estado', 'opcion', 'estado_brm', false, 570),
  ('sifon', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 580),
  ('sifon', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 590),
  ('sifon', 'insp_cobertura', 'Inspección · ¿La tubería cuenta con cobertura y/o protección?', 'opcion', 'si_no', true, 600),
  ('sifon', 'insp_cobertura_c', 'Inspección · ¿La tubería cuenta con cobertura y/o protección? — detalle', 'texto', NULL, false, 610),
  ('sifon', 'insp_corr_tub', 'Inspección · ¿Se evidencia desgaste por corrosión en la tubería de acero?', 'opcion', 'si_no', true, 620),
  ('sifon', 'insp_corr_tub_c', 'Inspección · ¿Se evidencia desgaste por corrosión en la tubería de acero? — detalle', 'texto', NULL, false, 630),
  ('sifon', 'insp_descarga', 'Inspección · ¿La zona de descarga de la purga se encuentra habilitada?', 'opcion', 'si_no', true, 640),
  ('sifon', 'insp_descarga_c', 'Inspección · ¿La zona de descarga de la purga se encuentra habilitada? — detalle', 'texto', NULL, false, 650),
  ('sifon', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 660),
  ('sublateral', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('sublateral', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('sublateral', 'prog_ini', 'Ubicación · progresiva inicio', 'texto', NULL, false, 30),
  ('sublateral', 'prog_fin', 'Ubicación · progresiva fin', 'texto', NULL, false, 40),
  ('sublateral', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('sublateral', 'sublat', 'Ubicación · sublateral', 'texto', NULL, false, 60),
  ('sublateral', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 70),
  ('sublateral', 'tipo', 'Obra · tipo de conducción', 'opcion', 'tipo_conduc', false, 80),
  ('sublateral', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 90),
  ('sublateral', 'red_tipo', 'Obra · troncal o secundaria', 'opcion', 'tipo_red', false, 100),
  ('sublateral', 'material', 'Obra · material de la tubería', 'opcion', 'material_tub', false, 110),
  ('sublateral', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 120),
  ('sublateral', 'q_diseno', 'Caudales · de diseño (m³/s)', 'numero', NULL, false, 130),
  ('sublateral', 'q_opera', 'Caudales · de operación (m³/s)', 'numero', NULL, false, 140),
  ('sublateral', 'uso', 'Caudales · tipo de uso', 'opcion', 'tipo_uso', false, 150),
  ('sublateral', 'n__usuario', 'Caudales · n° de usuarios', 'entero', NULL, false, 160),
  ('sublateral', 'area_total', 'Caudales · área total (ha)', 'numero', NULL, false, 170),
  ('sublateral', 'area_riego', 'Caudales · área bajo riego (ha)', 'numero', NULL, false, 180),
  ('sublateral', 'vol_otorg', 'Caudales · volumen otorgado (m³)', 'numero', NULL, false, 190),
  ('sublateral', 'cap_vent', 'Caudales · n° de ventanas de captación', 'entero', NULL, false, 200),
  ('sublateral', 'med_hay', 'Medición · ¿hay estructura al inicio?', 'opcion', 'si_no', false, 210),
  ('sublateral', 'med_tipo', 'Medición · tipo', 'opcion', 'tipo_medicion', false, 220),
  ('sublateral', 'med_otro', 'Medición · otro (especificar)', 'texto', NULL, false, 230),
  ('sublateral', 'med_estado', 'Medición · estado', 'opcion', 'estado_brm', false, 240),
  ('sublateral', 'cs_hay', 'Camino de servicio · ¿existe?', 'opcion', 'si_no', false, 250),
  ('sublateral', 'cs_margen', 'Camino de servicio · margen', 'opcion', 'margen_cs', false, 260),
  ('sublateral', 'cs_estado', 'Camino de servicio · estado', 'opcion', 'estado_brm', false, 270),
  ('sublateral', 'eh_cajas', 'Accesorios · cajas de inspección (und.)', 'entero', NULL, false, 280),
  ('sublateral', 'eh_valv', 'Accesorios · válvulas de aire (und.)', 'entero', NULL, false, 290),
  ('sublateral', 'eh_hidrom', 'Accesorios · hidrómetros (und.)', 'entero', NULL, false, 300),
  ('sublateral', 'eh_hidran', 'Accesorios · hidrantes (und.)', 'entero', NULL, false, 310),
  ('sublateral', 'eh_otros', 'Accesorios · otros', 'texto', NULL, false, 320),
  ('sublateral', 'dim_diam', 'Sección · diámetro D (mm)', 'numero', NULL, false, 330),
  ('sublateral', 'dim_pd', 'Sección · profundidad PD (m)', 'numero', NULL, false, 340),
  ('sublateral', 'dim_b', 'Sección · ancho de zanja B (m)', 'numero', NULL, false, 350),
  ('sublateral', 'dim_cs', 'Sección · camino de servicio CS (m)', 'numero', NULL, false, 360),
  ('sublateral', 'dim_x', 'Sección · x (m)', 'numero', NULL, false, 370),
  ('sublateral', 'dim_pend', 'Sección · pendiente S (%)', 'numero', NULL, false, 380),
  ('sublateral', 'insp_construcc', 'Inspección · ¿Existen construcciones sobre la tubería?', 'opcion', 'si_no', true, 390),
  ('sublateral', 'insp_construcc_c', 'Inspección · ¿Existen construcciones sobre la tubería? — detalle', 'texto', NULL, false, 400),
  ('sublateral', 'insp_pintado', 'Inspección · ¿Existe el pintado de progresivas y señalética en el tramo?', 'opcion', 'si_no', true, 410),
  ('sublateral', 'insp_pintado_c', 'Inspección · ¿Existe el pintado de progresivas y señalética en el tramo? — detalle', 'texto', NULL, false, 420),
  ('sublateral', 'insp_mant_cs', 'Inspección · ¿Se evidencia mantenimiento del camino de servicio?', 'opcion', 'si_no', true, 430),
  ('sublateral', 'insp_mant_cs_c', 'Inspección · ¿Se evidencia mantenimiento del camino de servicio? — detalle', 'texto', NULL, false, 440),
  ('sublateral', 'insp_tension', 'Inspección · ¿Existen líneas de alta, media o baja tensión sobre el emplazamiento?', 'opcion', 'si_no', true, 450),
  ('sublateral', 'insp_tension_c', 'Inspección · ¿Existen líneas de alta, media o baja tensión sobre el emplazamiento? — detalle', 'texto', NULL, false, 460),
  ('sublateral', 'insp_interfer', 'Inspección · ¿Existen interferencias en el tramo (líneas de riego, cerco perimétrico, otras)?', 'opcion', 'si_no', true, 470),
  ('sublateral', 'insp_interfer_c', 'Inspección · ¿Existen interferencias en el tramo (líneas de riego, cerco perimétrico, otras)? — detalle', 'texto', NULL, false, 480),
  ('sublateral', 'insp_acceso', 'Inspección · ¿El acceso a la tubería es restringido?', 'opcion', 'si_no', true, 490),
  ('sublateral', 'insp_acceso_c', 'Inspección · ¿El acceso a la tubería es restringido? — detalle', 'texto', NULL, false, 500),
  ('sublateral', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 510),
  ('tomas_canal_madre', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('tomas_canal_madre', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('tomas_canal_madre', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('tomas_canal_madre', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('tomas_canal_madre', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('tomas_canal_madre', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('tomas_canal_madre', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('tomas_canal_madre', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('tomas_canal_madre', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('tomas_canal_madre', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('tomas_canal_madre', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('tomas_canal_madre', 'q_diseno', 'Caudales · de diseño (m³/s)', 'numero', NULL, false, 120),
  ('tomas_canal_madre', 'q_opera', 'Caudales · de operación (m³/s)', 'numero', NULL, false, 130),
  ('tomas_canal_madre', 'uso', 'Caudales · tipo de uso', 'opcion', 'tipo_uso', false, 140),
  ('tomas_canal_madre', 'n__usuario', 'Caudales · n° de usuarios', 'entero', NULL, false, 150),
  ('tomas_canal_madre', 'area_total', 'Caudales · área total (ha)', 'numero', NULL, false, 160),
  ('tomas_canal_madre', 'area_riego', 'Caudales · área bajo riego (ha)', 'numero', NULL, false, 170),
  ('tomas_canal_madre', 'vol_otorg', 'Caudales · volumen otorgado (m³)', 'numero', NULL, false, 180),
  ('tomas_canal_madre', 'tom_estado', 'Toma · estado', 'opcion', 'estado_brm', false, 190),
  ('tomas_canal_madre', 'tom_ancho', 'Toma · ancho b (m)', 'numero', NULL, false, 200),
  ('tomas_canal_madre', 'tom_long2', 'Toma · longitud L2 (m)', 'numero', NULL, false, 210),
  ('tomas_canal_madre', 'tom_long3', 'Toma · longitud L3 (m)', 'numero', NULL, false, 220),
  ('tomas_canal_madre', 'tom_altura', 'Toma · altura h (m)', 'numero', NULL, false, 230),
  ('tomas_canal_madre', 'tom_espes', 'Toma · espesor muro e (m)', 'numero', NULL, false, 240),
  ('tomas_canal_madre', 'tom_esplos', 'Toma · espesor losa e1 (m)', 'numero', NULL, false, 250),
  ('tomas_canal_madre', 'tom_talud', 'Toma · talud Z (1:H)', 'numero', NULL, false, 260),
  ('tomas_canal_madre', 'com_ancho', 'Compuerta · ancho a (m)', 'numero', NULL, false, 270),
  ('tomas_canal_madre', 'com_alto', 'Compuerta · alto b (m)', 'numero', NULL, false, 280),
  ('tomas_canal_madre', 'com_htotal', 'Compuerta · altura total H (m)', 'numero', NULL, false, 290),
  ('tomas_canal_madre', 'com_eplan', 'Compuerta · espesor plancha (mm)', 'numero', NULL, false, 300),
  ('tomas_canal_madre', 'com_vast', 'Compuerta · vástago (pulg)', 'texto', NULL, false, 310),
  ('tomas_canal_madre', 'com_sello', 'Compuerta · ¿cuenta con sello?', 'opcion', 'si_no', false, 320),
  ('tomas_canal_madre', 'com_tsello', 'Compuerta · tipo de sello', 'texto', NULL, false, 330),
  ('tomas_canal_madre', 'com_esello', 'Compuerta · espesor de sello (mm)', 'numero', NULL, false, 340),
  ('tomas_canal_madre', 'compuertas', 'Compuerta · ¿cuenta con compuerta?', 'opcion', 'si_no', false, 350),
  ('tomas_canal_madre', 'com_mat', 'Compuerta · material', 'opcion', 'material_tub', false, 360),
  ('tomas_canal_madre', 'com_opera', 'Compuerta · operación', 'opcion', 'tipo_operacion', false, 370),
  ('tomas_canal_madre', 'com_estado', 'Compuerta · estado', 'opcion', 'estado_brm', false, 380),
  ('tomas_canal_madre', 'ret_hay', 'Retención · ¿cuenta con?', 'opcion', 'si_no', false, 390),
  ('tomas_canal_madre', 'ret_altura', 'Retención · altura h (m)', 'numero', NULL, false, 400),
  ('tomas_canal_madre', 'estado2', 'Retención · estado', 'opcion', 'estado_brm', false, 410),
  ('tomas_canal_madre', 'ret_purga', 'Retención · ¿compuerta de purga?', 'opcion', 'si_no', false, 420),
  ('tomas_canal_madre', 'ret_dimpur', 'Retención · dimensiones de la purga', 'texto', NULL, false, 430),
  ('tomas_canal_madre', 'material1', 'Retención · material', 'opcion', 'material_tub', false, 440),
  ('tomas_canal_madre', 'bar_hay', 'Baranda metálica · ¿cuenta con?', 'opcion', 'si_no', false, 450),
  ('tomas_canal_madre', 'bar_estado', 'Baranda metálica · estado', 'opcion', 'estado_brm', false, 460),
  ('tomas_canal_madre', 'sld_tipo', 'Salida · tipo', 'opcion', 'tipo_conduc', false, 470),
  ('tomas_canal_madre', 'sld_diam', 'Salida · diámetro Ø (mm)', 'numero', NULL, false, 480),
  ('tomas_canal_madre', 'sld_mat', 'Salida · material', 'opcion', 'material_tub', false, 490),
  ('tomas_canal_madre', 'sld_medic', 'Salida · ¿estructura de medición?', 'opcion', 'si_no', false, 500),
  ('tomas_canal_madre', 'sld_tmedic', 'Salida · tipo de medición', 'texto', NULL, false, 510),
  ('tomas_canal_madre', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 520),
  ('tomas_canal_madre', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 530),
  ('tomas_canal_madre', 'insp_metal_op', 'Inspección · ¿Las estructuras metálicas se encuentran operativas?', 'opcion', 'si_no', true, 540),
  ('tomas_canal_madre', 'insp_metal_op_c', 'Inspección · ¿Las estructuras metálicas se encuentran operativas? — detalle', 'texto', NULL, false, 550),
  ('tomas_canal_madre', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 560),
  ('tomas_canal_madre', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 570),
  ('tomas_canal_madre', 'insp_segurid', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación?', 'opcion', 'si_no', true, 580),
  ('tomas_canal_madre', 'insp_segurid_c', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación? — detalle', 'texto', NULL, false, 590),
  ('tomas_canal_madre', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 600),
  ('tomas_l10', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('tomas_l10', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('tomas_l10', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('tomas_l10', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('tomas_l10', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('tomas_l10', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('tomas_l10', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('tomas_l10', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('tomas_l10', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('tomas_l10', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('tomas_l10', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('tomas_l10', 'q_diseno', 'Caudales · de diseño (m³/s)', 'numero', NULL, false, 120),
  ('tomas_l10', 'operación', 'Caudales · de operación (m³/s)', 'numero', NULL, false, 130),
  ('tomas_l10', 'uso', 'Caudales · tipo de uso', 'opcion', 'tipo_uso', false, 140),
  ('tomas_l10', 'n__usuario', 'Caudales · n° de usuarios', 'entero', NULL, false, 150),
  ('tomas_l10', 'Áreas_tot', 'Caudales · área total (ha)', 'numero', NULL, false, 160),
  ('tomas_l10', 'Áreas_baj', 'Caudales · área bajo riego (ha)', 'numero', NULL, false, 170),
  ('tomas_l10', 'vol_otorg', 'Caudales · volumen otorgado (m³)', 'numero', NULL, false, 180),
  ('tomas_l10', 'tom_estado', 'Toma · estado', 'opcion', 'estado_brm', false, 190),
  ('tomas_l10', 'tom_ancho', 'Toma · ancho b (m)', 'numero', NULL, false, 200),
  ('tomas_l10', 'tom_long2', 'Toma · longitud L2 (m)', 'numero', NULL, false, 210),
  ('tomas_l10', 'tom_long3', 'Toma · longitud L3 (m)', 'numero', NULL, false, 220),
  ('tomas_l10', 'tom_altura', 'Toma · altura h (m)', 'numero', NULL, false, 230),
  ('tomas_l10', 'tom_espes', 'Toma · espesor muro e (m)', 'numero', NULL, false, 240),
  ('tomas_l10', 'tom_esplos', 'Toma · espesor losa e1 (m)', 'numero', NULL, false, 250),
  ('tomas_l10', 'tom_talud', 'Toma · talud Z (1:H)', 'numero', NULL, false, 260),
  ('tomas_l10', 'com_ancho', 'Compuerta · ancho a (m)', 'numero', NULL, false, 270),
  ('tomas_l10', 'com_alto', 'Compuerta · alto b (m)', 'numero', NULL, false, 280),
  ('tomas_l10', 'com_htotal', 'Compuerta · altura total H (m)', 'numero', NULL, false, 290),
  ('tomas_l10', 'com_eplan', 'Compuerta · espesor plancha (mm)', 'numero', NULL, false, 300),
  ('tomas_l10', 'com_vast', 'Compuerta · vástago (pulg)', 'texto', NULL, false, 310),
  ('tomas_l10', 'com_sello', 'Compuerta · ¿cuenta con sello?', 'opcion', 'si_no', false, 320),
  ('tomas_l10', 'com_tsello', 'Compuerta · tipo de sello', 'texto', NULL, false, 330),
  ('tomas_l10', 'com_esello', 'Compuerta · espesor de sello (mm)', 'numero', NULL, false, 340),
  ('tomas_l10', 'com_hay', 'Compuerta · ¿cuenta con compuerta?', 'opcion', 'si_no', false, 350),
  ('tomas_l10', 'com_mat', 'Compuerta · material', 'opcion', 'material_tub', false, 360),
  ('tomas_l10', 'operaci_1', 'Compuerta · operación', 'opcion', 'tipo_operacion', false, 370),
  ('tomas_l10', 'estado1', 'Compuerta · estado', 'opcion', 'estado_brm', false, 380),
  ('tomas_l10', 'ret_hay', 'Retención · ¿cuenta con?', 'opcion', 'si_no', false, 390),
  ('tomas_l10', 'ret_altura', 'Retención · altura h (m)', 'numero', NULL, false, 400),
  ('tomas_l10', 'estado2', 'Retención · estado', 'opcion', 'estado_brm', false, 410),
  ('tomas_l10', 'ret_purga', 'Retención · ¿compuerta de purga?', 'opcion', 'si_no', false, 420),
  ('tomas_l10', 'ret_dimpur', 'Retención · dimensiones de la purga', 'texto', NULL, false, 430),
  ('tomas_l10', 'ret_mat', 'Retención · material', 'opcion', 'material_tub', false, 440),
  ('tomas_l10', 'bar_hay', 'Baranda metálica · ¿cuenta con?', 'opcion', 'si_no', false, 450),
  ('tomas_l10', 'bar_estado', 'Baranda metálica · estado', 'opcion', 'estado_brm', false, 460),
  ('tomas_l10', 'sld_tipo', 'Salida · tipo', 'opcion', 'tipo_conduc', false, 470),
  ('tomas_l10', 'sld_diam', 'Salida · diámetro Ø (mm)', 'numero', NULL, false, 480),
  ('tomas_l10', 'sld_mat', 'Salida · material', 'opcion', 'material_tub', false, 490),
  ('tomas_l10', 'sld_medic', 'Salida · ¿estructura de medición?', 'opcion', 'si_no', false, 500),
  ('tomas_l10', 'sld_tmedic', 'Salida · tipo de medición', 'texto', NULL, false, 510),
  ('tomas_l10', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 520),
  ('tomas_l10', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 530),
  ('tomas_l10', 'insp_metal_op', 'Inspección · ¿Las estructuras metálicas se encuentran operativas?', 'opcion', 'si_no', true, 540),
  ('tomas_l10', 'insp_metal_op_c', 'Inspección · ¿Las estructuras metálicas se encuentran operativas? — detalle', 'texto', NULL, false, 550),
  ('tomas_l10', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 560),
  ('tomas_l10', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 570),
  ('tomas_l10', 'insp_segurid', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación?', 'opcion', 'si_no', true, 580),
  ('tomas_l10', 'insp_segurid_c', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación? — detalle', 'texto', NULL, false, 590),
  ('tomas_l10', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 600),
  ('tomas_otros_sectores', 'estado', 'Estado de conservación', 'opcion', 'estado_brm', true, 10),
  ('tomas_otros_sectores', 'observacio', 'Condición operativa', 'opcion', 'condicion_operativa', true, 20),
  ('tomas_otros_sectores', 'progresiva', 'Ubicación · progresiva', 'texto', NULL, false, 30),
  ('tomas_otros_sectores', 'margen', 'Ubicación · margen (D o I)', 'opcion', 'margen', false, 40),
  ('tomas_otros_sectores', 'obs_ubic', 'Ubicación · observaciones', 'texto', NULL, false, 50),
  ('tomas_otros_sectores', 'anio_const', 'Obra · año de construcción', 'entero', NULL, false, 60),
  ('tomas_otros_sectores', 'tipo', 'Obra · tipo', 'opcion', 'tipo_obra', false, 70),
  ('tomas_otros_sectores', 'tipo_otro', 'Obra · tipo (otro)', 'texto', NULL, false, 80),
  ('tomas_otros_sectores', 'material', 'Obra · material', 'opcion', 'material_obra', false, 90),
  ('tomas_otros_sectores', 'mat_estado', 'Obra · estado del material', 'opcion', 'estado_brm', false, 100),
  ('tomas_otros_sectores', 'mat_otro', 'Obra · material (otros)', 'texto', NULL, false, 110),
  ('tomas_otros_sectores', 'q_diseno', 'Caudales · de diseño (m³/s)', 'numero', NULL, false, 120),
  ('tomas_otros_sectores', 'caudal_m3_', 'Caudales · de operación (m³/s)', 'numero', NULL, false, 130),
  ('tomas_otros_sectores', 'uso', 'Caudales · tipo de uso', 'opcion', 'tipo_uso', false, 140),
  ('tomas_otros_sectores', 'n__usuario', 'Caudales · n° de usuarios', 'entero', NULL, false, 150),
  ('tomas_otros_sectores', 'area_total', 'Caudales · área total (ha)', 'numero', NULL, false, 160),
  ('tomas_otros_sectores', 'area_riego', 'Caudales · área bajo riego (ha)', 'numero', NULL, false, 170),
  ('tomas_otros_sectores', 'vol_otorg', 'Caudales · volumen otorgado (m³)', 'numero', NULL, false, 180),
  ('tomas_otros_sectores', 'tom_estado', 'Toma · estado', 'opcion', 'estado_brm', false, 190),
  ('tomas_otros_sectores', 'tom_ancho', 'Toma · ancho b (m)', 'numero', NULL, false, 200),
  ('tomas_otros_sectores', 'tom_long2', 'Toma · longitud L2 (m)', 'numero', NULL, false, 210),
  ('tomas_otros_sectores', 'tom_long3', 'Toma · longitud L3 (m)', 'numero', NULL, false, 220),
  ('tomas_otros_sectores', 'tom_altura', 'Toma · altura h (m)', 'numero', NULL, false, 230),
  ('tomas_otros_sectores', 'tom_espes', 'Toma · espesor muro e (m)', 'numero', NULL, false, 240),
  ('tomas_otros_sectores', 'tom_esplos', 'Toma · espesor losa e1 (m)', 'numero', NULL, false, 250),
  ('tomas_otros_sectores', 'tom_talud', 'Toma · talud Z (1:H)', 'numero', NULL, false, 260),
  ('tomas_otros_sectores', 'com_ancho', 'Compuerta · ancho a (m)', 'numero', NULL, false, 270),
  ('tomas_otros_sectores', 'com_alto', 'Compuerta · alto b (m)', 'numero', NULL, false, 280),
  ('tomas_otros_sectores', 'com_htotal', 'Compuerta · altura total H (m)', 'numero', NULL, false, 290),
  ('tomas_otros_sectores', 'com_eplan', 'Compuerta · espesor plancha (mm)', 'numero', NULL, false, 300),
  ('tomas_otros_sectores', 'com_vast', 'Compuerta · vástago (pulg)', 'texto', NULL, false, 310),
  ('tomas_otros_sectores', 'com_sello', 'Compuerta · ¿cuenta con sello?', 'opcion', 'si_no', false, 320),
  ('tomas_otros_sectores', 'com_tsello', 'Compuerta · tipo de sello', 'texto', NULL, false, 330),
  ('tomas_otros_sectores', 'com_esello', 'Compuerta · espesor de sello (mm)', 'numero', NULL, false, 340),
  ('tomas_otros_sectores', 'com_hay', 'Compuerta · ¿cuenta con compuerta?', 'opcion', 'si_no', false, 350),
  ('tomas_otros_sectores', 'com_mat', 'Compuerta · material', 'opcion', 'material_tub', false, 360),
  ('tomas_otros_sectores', 'com_opera', 'Compuerta · operación', 'opcion', 'tipo_operacion', false, 370),
  ('tomas_otros_sectores', 'com_estado', 'Compuerta · estado', 'opcion', 'estado_brm', false, 380),
  ('tomas_otros_sectores', 'ret_hay', 'Retención · ¿cuenta con?', 'opcion', 'si_no', false, 390),
  ('tomas_otros_sectores', 'ret_altura', 'Retención · altura h (m)', 'numero', NULL, false, 400),
  ('tomas_otros_sectores', 'ret_estado', 'Retención · estado', 'opcion', 'estado_brm', false, 410),
  ('tomas_otros_sectores', 'ret_purga', 'Retención · ¿compuerta de purga?', 'opcion', 'si_no', false, 420),
  ('tomas_otros_sectores', 'ret_dimpur', 'Retención · dimensiones de la purga', 'texto', NULL, false, 430),
  ('tomas_otros_sectores', 'ret_mat', 'Retención · material', 'opcion', 'material_tub', false, 440),
  ('tomas_otros_sectores', 'bar_hay', 'Baranda metálica · ¿cuenta con?', 'opcion', 'si_no', false, 450),
  ('tomas_otros_sectores', 'bar_estado', 'Baranda metálica · estado', 'opcion', 'estado_brm', false, 460),
  ('tomas_otros_sectores', 'sld_tipo', 'Salida · tipo', 'opcion', 'tipo_conduc', false, 470),
  ('tomas_otros_sectores', 'sld_diam', 'Salida · diámetro Ø (mm)', 'numero', NULL, false, 480),
  ('tomas_otros_sectores', 'sld_mat', 'Salida · material', 'opcion', 'material_tub', false, 490),
  ('tomas_otros_sectores', 'sld_medic', 'Salida · ¿estructura de medición?', 'opcion', 'si_no', false, 500),
  ('tomas_otros_sectores', 'sld_tmedic', 'Salida · tipo de medición', 'texto', NULL, false, 510),
  ('tomas_otros_sectores', 'insp_concreto', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)?', 'opcion', 'si_no', true, 520),
  ('tomas_otros_sectores', 'insp_concreto_c', 'Inspección · ¿Problemas en el concreto armado (fisuras, corrosión de armaduras, desgaste)? — detalle', 'texto', NULL, false, 530),
  ('tomas_otros_sectores', 'insp_metal_op', 'Inspección · ¿Las estructuras metálicas se encuentran operativas?', 'opcion', 'si_no', true, 540),
  ('tomas_otros_sectores', 'insp_metal_op_c', 'Inspección · ¿Las estructuras metálicas se encuentran operativas? — detalle', 'texto', NULL, false, 550),
  ('tomas_otros_sectores', 'insp_rebasada', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)?', 'opcion', 'si_no', true, 560),
  ('tomas_otros_sectores', 'insp_rebasada_c', 'Inspección · ¿Fue rebasada en época de crecidas (fenómenos extraordinarios)? — detalle', 'texto', NULL, false, 570),
  ('tomas_otros_sectores', 'insp_segurid', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación?', 'opcion', 'si_no', true, 580),
  ('tomas_otros_sectores', 'insp_segurid_c', 'Inspección · ¿Cuenta con elementos de seguridad y señalética para su operación? — detalle', 'texto', NULL, false, 590),
  ('tomas_otros_sectores', 'nota_adic', 'Inspección · notas adicionales', 'texto', NULL, false, 600);

-- ── 3) Insertar lo que falta, solo de tipos que existen ─────────────────
INSERT INTO campos_evaluables (tipo_activo, campo, etiqueta, tipo_dato,
                               dominio, obligatorio, orden)
SELECT k.tipo_activo, k.campo, k.etiqueta, k.tipo_dato,
       k.dominio, k.obligatorio, k.orden
FROM catalogo k
WHERE EXISTS (SELECT 1 FROM tipos_activo t WHERE t.codigo = k.tipo_activo)
  AND NOT EXISTS (
    SELECT 1 FROM campos_evaluables c
    WHERE c.tipo_activo = k.tipo_activo AND c.campo = k.campo
  );

-- ── 4) Alinear lo que ya estaba ─────────────────────────────────────────
UPDATE campos_evaluables c
SET etiqueta    = k.etiqueta,
    tipo_dato   = k.tipo_dato,
    dominio     = k.dominio,
    obligatorio = k.obligatorio,
    orden       = k.orden
FROM catalogo k
WHERE c.tipo_activo = k.tipo_activo
  AND c.campo = k.campo
  AND (c.etiqueta, c.tipo_dato, c.dominio, c.obligatorio, c.orden)
      IS DISTINCT FROM
      (k.etiqueta, k.tipo_dato, k.dominio, k.obligatorio, k.orden);

-- ── 5) Los tipos del catálogo quedan marcados como evaluables ───────────
UPDATE tipos_activo t SET evaluable = true
WHERE EXISTS (SELECT 1 FROM catalogo k WHERE k.tipo_activo = t.codigo)
  AND NOT t.evaluable;

-- ── 6) Avisos y guardas ─────────────────────────────────────────────────
DO $$
DECLARE faltan text; sobran text; sin_dom text;
BEGIN
  -- Un desplegable sin opciones se ve igual que un campo roto en el
  -- teléfono, y en campo no hay a quién preguntarle. Esto aborta.
  SELECT string_agg(DISTINCT c.dominio, ', ') INTO sin_dom
  FROM campos_evaluables c
  WHERE EXISTS (SELECT 1 FROM catalogo k WHERE k.tipo_activo = c.tipo_activo)
    AND c.dominio IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM dominios d WHERE d.dominio = c.dominio);
  IF sin_dom IS NOT NULL THEN
    RAISE EXCEPTION 'hay campos apuntando a dominios que no existen: %', sin_dom;
  END IF;

  -- Tipos del catálogo que no están en la base: hay que crearlos o
  -- corregir el código en el generador.
  SELECT string_agg(DISTINCT k.tipo_activo, ', ') INTO faltan
  FROM catalogo k
  WHERE NOT EXISTS (SELECT 1 FROM tipos_activo t WHERE t.codigo = k.tipo_activo);
  IF faltan IS NOT NULL THEN
    RAISE NOTICE 'NO se cargaron estos tipos porque no existen en tipos_activo: %', faltan;
    RAISE NOTICE 'Revisa el SELECT de arriba, corrige el codigo y vuelve a correr.';
  END IF;

  -- Campos que están en la base y no en el catálogo: no se borran solos.
  SELECT string_agg(c.tipo_activo || '.' || c.campo, ', ') INTO sobran
  FROM campos_evaluables c
  WHERE EXISTS (SELECT 1 FROM catalogo k WHERE k.tipo_activo = c.tipo_activo)
    AND NOT EXISTS (SELECT 1 FROM catalogo k
                    WHERE k.tipo_activo = c.tipo_activo AND k.campo = c.campo);
  IF sobran IS NOT NULL THEN
    RAISE NOTICE 'campos fuera del catalogo, revisalos a mano: %', sobran;
  END IF;
END $$;

COMMIT;

-- ── 7) Comprobación ─────────────────────────────────────────────────────
SELECT t.codigo,
       t.nombre,
       count(c.campo)                                AS campos,
       count(c.campo) FILTER (WHERE c.obligatorio)   AS obligatorios
FROM tipos_activo t
LEFT JOIN campos_evaluables c ON c.tipo_activo = t.codigo
GROUP BY t.codigo, t.nombre
HAVING count(c.campo) > 0
ORDER BY t.codigo;
